[package]
name = "tesla_auth"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oauth2 = "4.1.0"
reqwest = { version = "0.11.4" , default-features = false, features = ["json", "rustls-tls"]}
serde = "1.0.130"
serde_json = "1.0.67"
wry = { version = "0.12", default-features = false, features = [] }

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
