[package]
name = "tesla_auth"
version = "0.5.3"
description = "Tesla token generator"
homepage = "https://github.com/adriankumpf/tesla_auth"
repository = "https://github.com/adriankumpf/tesla_auth"
keywords = ["tesla-api", "oauth2", "webview", "cli"]
categories = ["command-line-utilities"]
authors = ["Adrian Kumpf"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
argh = "0.1.9"
log = "0.4.17"
oauth2 = "4.2.3"
reqwest = { version = "0.11.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
serde_json = "1.0.85"
simple_logger = { version = "2.3.0", default-features = false, features = ["stderr"] }
wry = { version = "0.21.1", default-features = false, features = [] }

[build-dependencies]
static_vcruntime = "2.0.0"

[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
